version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - '9092:9092'
      - '9101:9101'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  postgres:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

  # glue_jupyter_lab:
  #   image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
  #   hostname: glue_lab
  #   container_name: glue_lab
  #   command: /home/glue_user/jupyter/jupyter_start.sh
  #   ports:
  #     - '8888:8888'
  #     - '8889:8889'
  #     - '4040:4040'
  #     - '18080:18080'
  #   volumes:
  #     - ${PWD}:/home/glue_user/workspace/
  #   environment:
  #     AWS_ACCESS_KEY_ID: AKIAW35NHIMCLFAJE7WE
  #     AWS_SECRET_ACCESS_KEY: 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
  #     DISABLE_SSL: 0
